const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

const CALL_USER = "CALL_USER";
const INCOMING_CALL = "INCOMING_CALL";
const ANSWER_CALL = " ANSWER_CALL";
const CALL_ANSWERED = "CALL_ANSWERED";
const SEND_ICE_CANDIDATE = "SEND_ICE_CANDIDATE ";
const RECEIVE_ICE_CANDIDATE = "RECEIVE_ICE_CANDIDATE";


export {
  CALL_USER,
  RECEIVE_ICE_CANDIDATE,
  SEND_ICE_CANDIDATE,
  CALL_ANSWERED,
  ANSWER_CALL,
  INCOMING_CALL,
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
};
